### ISSUE TITLE
Make the nosetests functional from the 'make test' call

### ISSUE THREAD

**Issue by tmcclintock** [erykoff/redmapper#10]
The nosetests work fine at the moment if they are called from within the tests/ directory. They are meant to be run from the root with
```
make test
```
however this fails because of pathing issues, since the unit tests are written assuming they are being run from within the tests/ directory.

**Comment by erykoff** [comment]
Because "import redmapper" will import from the local directory before the installed/compiled version, "make test" will always fail from the main directory (and not from the tests directory) because it can't find the compiled c code.  I don't know how to change this behavior...

**Comment by tmcclintock** [comment]
I'm going to close this since we will have users run the nosetests in a different way.
