### ISSUE TITLE
Compute lambda_chisq for a single test cluster

### ISSUE THREAD

**Issue by erykoff** [erykoff/redmapper#12]

**Comment by tmcclintock** [comment]
This is done in redmapper/cluster.py in the calc_richness() function.

**Comment by tmcclintock** [comment]
A unit test found in test/test_clusters.py for this is being implemented in the function test_calc_richness(), however this is suffering from a bug.

At the moment, calc_richness() requires a field called 'dist' for the cluster members. This field is not found in the test_cluster_members.fit file.

FOR NOW, in test/test_clusters.py I am setting **members.dist** to be equal to members.r**.

**Comment by erykoff** [comment]
So this is a problem with the test data/workflow, I suppose.  The intention is that `dist` is in arcseconds and `r` is in h^-1 Mpc.  Note that dist is a computed quantity that comes from cluster.find_members() (which also needs to be tested). `r` can then be computed from `dist` and `z` for the cluster.
For a more atomic test of the cluster richness code, then `dist` should be in there, but for a broader test of the code we should take the galaxy catalog and cluster centers, match them (and compute `dist`) and then compute richness in the "regular" workflow.

**Comment by erykoff** [comment]
hmm.  Now that I think about it, the test_cluster_members.fit should not be used as an input to the test, but as a comparison to the output from the test.

**Comment by tmcclintock** [comment]
What data should be used in this case? Just the galaxy catalog?

**Comment by tmcclintock** [comment]
We need a new test data file. Looking, for instance, at pixelized_dr8_test/dr8_test_galaxies_0008421.fit, the galaxies in that file do not have redshifts. The master table also only contains healpix specific data.

**Comment by erykoff** [comment]
What we need is a list of clusters in the test footprint.  Galaxies don't come with redshifts...

**Comment by erykoff** [comment]
A test cluster is at 142.12752, 65.103898, z=0.228654
