### ISSUE TITLE
the RedSequenceColorPar is missing limmag

### ISSUE THREAD

**Issue by tmcclintock** [erykoff/redmapper#19]
We need limmag to calculate theta_i in cluster.calc_richness().

Limmag comes from the zredstr. The file used to create this in testing is test_dr8_pars.fit. This file is missing limmag, alpha, mstarsur, mstarban, and ncol.

**Comment by erykoff** [comment]
We will need the local specific limmag, which should come from the depth map (via maskgals).  The survey information, including those other parameters, are recorded in the fits header for test_dr8_pars.fit, and I just pushed self. terms to make them available.

**Comment by tmcclintock** [comment]
All fixed.
