### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by tmcclintock** [erykoff/redmapper#22]
I have downloaded the most recent version of the algorithm in this repository and ran the unit tests found in the `tests` directory at the command line using `python test_X.py`. Two tests (`centeringcal` and `selectspecred` failed with these outputs:
```
$ python test_centeringcal.py 
F
======================================================================
FAIL: test_centeringcal (__main__.CenteringCalibratorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_centeringcal.py", line 59, in test_centeringcal
    testing.assert_almost_equal(config.lnw_fg_mean, -0.26910934330307562, 5)
  File "/Users/tmcclintock/anaconda/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 584, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 5 decimals
 ACTUAL: -0.2691507977537982
 DESIRED: -0.2691093433030756

----------------------------------------------------------------------
Ran 1 test in 5.751s

FAILED (failures=1)
```

```
$ python test_selectspecred.py 
Working on color 1
Working on color 2
Working on color 3
F
======================================================================
FAIL: test_selectred (__main__.SelectSpecRedTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_selectspecred.py", line 49, in test_selectred
    np.array([0.78117073, 1.08723211, 1.47198153]), 5)
  File "/Users/tmcclintock/anaconda/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 568, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/Users/tmcclintock/anaconda/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 973, in assert_array_almost_equal
    precision=decimal)
  File "/Users/tmcclintock/anaconda/lib/python2.7/site-packages/numpy/testing/_private/utils.py", line 789, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 5 decimals

(mismatch 100.0%)
 x: array([0.78204, 1.08707, 1.47274], dtype=float32)
 y: array([0.78117, 1.08723, 1.47198])

----------------------------------------------------------------------
Ran 1 test in 2.093s

FAILED (failures=1)
```

I ran with Python 2.7.13 and numpy 1.15.2. Should these accuracy requirements be at the 5 decimal level? Or is that too strict?

**Comment by erykoff** [comment]
Hmm.  After I patched the requirements.txt to avoid trying to download a python3-only version of matplotlib, it passes Travis.  With numpy 1.15.2 fwiw.  Not sure what's different on your system.

**Comment by tmcclintock** [comment]
Same. Perhaps its the C compiler? Was any of the C code called when these tests ran?

**Comment by erykoff** [comment]
The c code is compiled as part of the tests, but it doesn't seem that those tests that directly touch the c code have failed.  Do you get the same failures -- with the same numbers -- when running `nosetests` to run all of the tests as when running them individually? (Wondering if there could be some problematic global state, but I don't know how...)

**Comment by tmcclintock** [comment]
Yes, both fail with `nosetests` as well. My guess is that it's because I'm compiling with clang, but that's only because I can't think of anything else...

**Comment by erykoff** [comment]
The good news is that I can duplicate this on my mac, so I can hopefully figure out what's going on.

**Comment by erykoff** [comment]
@tmcclintock Can you check out the current master and see if it works for you now?

**Comment by tmcclintock** [comment]
Woohoo! Both work now. Feel free to close.
