### ISSUE TITLE
howto calibration example yaml file is outdated

### ISSUE THREAD

**Issue by jacobic** [erykoff/redmapper#55]
Some default parameters have been removed from the redmapper config class so the example calibration file no longer works with SDSS. Attached is a screenshot of the diff. The left shows the modifications (comments) to get things to work.

![Screenshot 2020-02-28 at 15 26 39](https://user-images.githubusercontent.com/9905226/75556746-116cbd80-5a3f-11ea-90cb-c35e1222b4b1.png)

Cheers,
Jacob

**Comment by erykoff** [comment]
Thanks.  Fixed with #56
