### ISSUE TITLE
Duplicate member 'id' in redMaPPer clusters when using Cardinal simulation

### ISSUE THREAD

**Issue by ShuleiCao** [erykoff/redmapper#92]
I've been working with the Cardinal simulation to generate redMaPPer catalogs. In the process of cross-referencing the redMaPPer member 'id' with the 'coadd_object_id' from the Cardinal gold catalog, I noticed inconsistencies. Upon closer inspection, I found:

- Some redMaPPer members from distinct clusters (differing in 'mem_match_id' and 'z' values) have the same member 'id', 'ra', and 'dec'.
- These duplicate member 'id' values persist even though there are differences in other quantities between the members.

This observation suggests that the redMaPPer member 'id' might not be unique, which is concerning for data matching and integrity. Can you provide insights on this behavior or indicate if it's a known issue?

**Comment by erykoff** [comment]
The redMaPPer algorithm is probabilistic (that's one of the Ps in redMaPPer) so a given galaxy can be possibly a member of more than one cluster (even at different redshifts, consistent with the galaxy colors).  The key, though, is that the total `p_mem` for any given galaxy may not exceed 1.0.  If you find that is the case, that is a bug.

So each galaxy should have a unique `z_red` (which is evaluated from the colors and nothing else), but may be listed in multiple clusters.  And any algorithm that is matching to "truth" in something like Cardinal would have to take that into account, as it's a fundamental property of the catalog.

Hope this helps!

**Comment by ShuleiCao** [comment]
> The redMaPPer algorithm is probabilistic (that's one of the Ps in redMaPPer) so a given galaxy can be possibly a member of more than one cluster (even at different redshifts, consistent with the galaxy colors). The key, though, is that the total `p_mem` for any given galaxy may not exceed 1.0. If you find that is the case, that is a bug.
> 
> So each galaxy should have a unique `z_red` (which is evaluated from the colors and nothing else), but may be listed in multiple clusters. And any algorithm that is matching to "truth" in something like Cardinal would have to take that into account, as it's a fundamental property of the catalog.
> 
> Hope this helps!

Thank you for the clarification regarding the probabilistic nature of the redMaPPer algorithm. It provides a clearer understanding of how a galaxy can potentially be a member of multiple clusters.

However, I have noticed a few peculiarities in the member lists:

1. **Presence of `p_free = 0` and `p = 0` Galaxies as Members**: My understanding was that if `p_free = 0`, it indicates that a galaxy's membership is fully accounted for by higher-ranked clusters. Consequently, I would expect that such galaxies should not have a p = 0 entry in the member list of any other cluster. Could you shed some light on this?
2. **Clarification on the Definition of `p`**: Is `p` equivalent to `p_mem`, or is it the product `p_mem * p_free`? I've observed members where `p` is non-zero, but `p_mem` is zero. Additionally, there are cases where the ratio `p/p_free` exceeds 1. Are these scenarios expected?

I appreciate your time and insights on this matter.

Thanks,
Shulei
